### ISSUE TITLE
на b-button свойство  line-height

### ISSUE THREAD

**Issue by MSupreme1990** [studio107/flexy#10]
Когда мы убираем стили line-height: normal , кнопка становится по всей высоте строки.

**Comment by max107** [comment]
Но, если поставить рядом `button` и `a`, то получаем следующее:

![screen shot 2017-06-15 at 16 52 52](https://user-images.githubusercontent.com/862272/27184530-1d7c46ea-51eb-11e7-8c29-57c08795990a.png)

```html
<button class="b-button">Hello world</button>
<a href="javascript:void(0)" class="b-button">button</a>
```
