### ISSUE TITLE
Методология

### ISSUE THREAD

**Issue by max107** [studio107/flexy#7]
От использования БЕМ в чистом виде принято решение отказаться.

Предлагаемый вариант со структурой файлов:

```
/scss/block/_header.scss
/scss/block/product/_product-list.scss
/scss/block/product/_product-item.scss
/scss/global.scss
/scss/screen.scss
```

Именование:

```

.header {
     .header-logo {
          // code...
     }

     .header-menu {
         // code ...
     }
}

```

**Comment by max107** [comment]
Не подходит для случаев:

```scss
.product-slider > .slider-item > .product-image-slider > .slider-item
```

**Comment by kvashonin** [comment]
чтобы структура была плоской придется писать так
```scss
.header {
     &-logo {
          // code...
     }

     &-menu {
         // code ...
     }
}
```

**Comment by max107** [comment]
Опять возвращаемся к тому, что будут проблемы при поиске по проекту. Вроде это кажется ерундой, но тратить 15 минут на поиск вместо 1 минуты, это критично. Лень двигатель прогресса.

Может все же так?

```scss
.header {}
.header-logo {}
.header-menu {}
```

без `&-foobar` ?
